In [3]:
import numpy as np

In [4]:
a = np.array([[9,5,3,1],
              [4,6,2,4]])

In [7]:
b = np.array([0,3,2,3])

In [8]:
a+b

array([[9, 8, 5, 4],
       [4, 9, 4, 7]])

In [77]:
b.shape

(2,)

In [78]:
a

array([[0, 5, 3, 1],
       [7, 6, 2, 0]])

In [58]:
x2 = np.sum(a**2, axis=1).reshape((4, 1))
y2 = np.sum(b**2, axis=1).reshape((1, 3))

In [59]:
x2

array([[130],
       [ 61],
       [ 25],
       [  5]])

In [63]:
y2

array([[ 25,   5, 100]])

In [66]:
(x2-y2)**2

array([[11025, 15625,   900],
       [ 1296,  3136,  1521],
       [    0,   400,  5625],
       [  400,     0,  9025]])

In [70]:
xy = a.dot(b.T) # shape is (m, n)
dists = x2 + y2 - 2*xy # shape is (m, n)

In [71]:
dists

array([[45, 89, 10],
       [ 8, 32,  5],
       [ 0,  8, 25],
       [ 8,  0, 61]])